version: '3.7'
services:
  attestor:
    build:
      context: .
      dockerfile: attestor.dockerfile
    env_file:
      - ".env.test"  # Using test env for development
    ports:
      - 8001:8001
    restart: on-failure
    